/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 71
#define LARGE_STATE_COUNT 11
#define SYMBOL_COUNT 54
#define ALIAS_COUNT 0
#define TOKEN_COUNT 34
#define EXTERNAL_TOKEN_COUNT 4
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LPAREN = 1,
  anon_sym_RPAREN = 2,
  anon_sym_LBRACE = 3,
  anon_sym_COMMA = 4,
  anon_sym_RBRACE = 5,
  anon_sym_LBRACK = 6,
  anon_sym_RBRACK = 7,
  anon_sym_DQUOTE_DQUOTE = 8,
  anon_sym_SQUOTE = 9,
  sym_float = 10,
  anon_sym_true = 11,
  anon_sym_false = 12,
  sym_null = 13,
  sym_identifier = 14,
  anon_sym_COLON = 15,
  sym_plain_key = 16,
  anon_sym_DQUOTE = 17,
  anon_sym_r = 18,
  anon_sym_b_DQUOTE = 19,
  anon_sym_br = 20,
  anon_sym_b64_DQUOTE = 21,
  sym_base64_content = 22,
  sym_temporal_content = 23,
  sym_decimal_integer = 24,
  sym_hex_integer = 25,
  sym_octal_integer = 26,
  sym_binary_integer = 27,
  sym_line_comment = 28,
  sym_block_comment = 29,
  sym_raw_start = 30,
  sym_raw_content = 31,
  sym_raw_end = 32,
  sym_quoted_content = 33,
  sym_duper_value = 34,
  sym_identified_value = 35,
  sym__value = 36,
  sym_object = 37,
  sym_array = 38,
  sym_tuple = 39,
  sym_string = 40,
  sym_bytes = 41,
  sym_temporal = 42,
  sym_integer = 43,
  sym_boolean = 44,
  sym_object_entry = 45,
  sym_object_key = 46,
  sym_quoted_string = 47,
  sym_raw_string = 48,
  sym_quoted_bytes = 49,
  sym_raw_bytes = 50,
  sym_base64_bytes = 51,
  aux_sym_object_repeat1 = 52,
  aux_sym_array_repeat1 = 53,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LBRACE] = "{",
  [anon_sym_COMMA] = ",",
  [anon_sym_RBRACE] = "}",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_DQUOTE_DQUOTE] = "\"\"",
  [anon_sym_SQUOTE] = "'",
  [sym_float] = "float",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_null] = "null",
  [sym_identifier] = "identifier",
  [anon_sym_COLON] = ":",
  [sym_plain_key] = "plain_key",
  [anon_sym_DQUOTE] = "\"",
  [anon_sym_r] = "r",
  [anon_sym_b_DQUOTE] = "b\"",
  [anon_sym_br] = "br",
  [anon_sym_b64_DQUOTE] = "b64\"",
  [sym_base64_content] = "base64_content",
  [sym_temporal_content] = "temporal_content",
  [sym_decimal_integer] = "decimal_integer",
  [sym_hex_integer] = "hex_integer",
  [sym_octal_integer] = "octal_integer",
  [sym_binary_integer] = "binary_integer",
  [sym_line_comment] = "line_comment",
  [sym_block_comment] = "block_comment",
  [sym_raw_start] = "raw_start",
  [sym_raw_content] = "raw_content",
  [sym_raw_end] = "raw_end",
  [sym_quoted_content] = "quoted_content",
  [sym_duper_value] = "duper_value",
  [sym_identified_value] = "identified_value",
  [sym__value] = "_value",
  [sym_object] = "object",
  [sym_array] = "array",
  [sym_tuple] = "tuple",
  [sym_string] = "string",
  [sym_bytes] = "bytes",
  [sym_temporal] = "temporal",
  [sym_integer] = "integer",
  [sym_boolean] = "boolean",
  [sym_object_entry] = "object_entry",
  [sym_object_key] = "object_key",
  [sym_quoted_string] = "quoted_string",
  [sym_raw_string] = "raw_string",
  [sym_quoted_bytes] = "quoted_bytes",
  [sym_raw_bytes] = "raw_bytes",
  [sym_base64_bytes] = "base64_bytes",
  [aux_sym_object_repeat1] = "object_repeat1",
  [aux_sym_array_repeat1] = "array_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_DQUOTE_DQUOTE] = anon_sym_DQUOTE_DQUOTE,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [sym_float] = sym_float,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_null] = sym_null,
  [sym_identifier] = sym_identifier,
  [anon_sym_COLON] = anon_sym_COLON,
  [sym_plain_key] = sym_plain_key,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [anon_sym_r] = anon_sym_r,
  [anon_sym_b_DQUOTE] = anon_sym_b_DQUOTE,
  [anon_sym_br] = anon_sym_br,
  [anon_sym_b64_DQUOTE] = anon_sym_b64_DQUOTE,
  [sym_base64_content] = sym_base64_content,
  [sym_temporal_content] = sym_temporal_content,
  [sym_decimal_integer] = sym_decimal_integer,
  [sym_hex_integer] = sym_hex_integer,
  [sym_octal_integer] = sym_octal_integer,
  [sym_binary_integer] = sym_binary_integer,
  [sym_line_comment] = sym_line_comment,
  [sym_block_comment] = sym_block_comment,
  [sym_raw_start] = sym_raw_start,
  [sym_raw_content] = sym_raw_content,
  [sym_raw_end] = sym_raw_end,
  [sym_quoted_content] = sym_quoted_content,
  [sym_duper_value] = sym_duper_value,
  [sym_identified_value] = sym_identified_value,
  [sym__value] = sym__value,
  [sym_object] = sym_object,
  [sym_array] = sym_array,
  [sym_tuple] = sym_tuple,
  [sym_string] = sym_string,
  [sym_bytes] = sym_bytes,
  [sym_temporal] = sym_temporal,
  [sym_integer] = sym_integer,
  [sym_boolean] = sym_boolean,
  [sym_object_entry] = sym_object_entry,
  [sym_object_key] = sym_object_key,
  [sym_quoted_string] = sym_quoted_string,
  [sym_raw_string] = sym_raw_string,
  [sym_quoted_bytes] = sym_quoted_bytes,
  [sym_raw_bytes] = sym_raw_bytes,
  [sym_base64_bytes] = sym_base64_bytes,
  [aux_sym_object_repeat1] = aux_sym_object_repeat1,
  [aux_sym_array_repeat1] = aux_sym_array_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [sym_float] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_null] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_plain_key] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_r] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_b_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_br] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_b64_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [sym_base64_content] = {
    .visible = true,
    .named = true,
  },
  [sym_temporal_content] = {
    .visible = true,
    .named = true,
  },
  [sym_decimal_integer] = {
    .visible = true,
    .named = true,
  },
  [sym_hex_integer] = {
    .visible = true,
    .named = true,
  },
  [sym_octal_integer] = {
    .visible = true,
    .named = true,
  },
  [sym_binary_integer] = {
    .visible = true,
    .named = true,
  },
  [sym_line_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_block_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_raw_start] = {
    .visible = true,
    .named = true,
  },
  [sym_raw_content] = {
    .visible = true,
    .named = true,
  },
  [sym_raw_end] = {
    .visible = true,
    .named = true,
  },
  [sym_quoted_content] = {
    .visible = true,
    .named = true,
  },
  [sym_duper_value] = {
    .visible = true,
    .named = true,
  },
  [sym_identified_value] = {
    .visible = true,
    .named = true,
  },
  [sym__value] = {
    .visible = false,
    .named = true,
  },
  [sym_object] = {
    .visible = true,
    .named = true,
  },
  [sym_array] = {
    .visible = true,
    .named = true,
  },
  [sym_tuple] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_bytes] = {
    .visible = true,
    .named = true,
  },
  [sym_temporal] = {
    .visible = true,
    .named = true,
  },
  [sym_integer] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [sym_object_entry] = {
    .visible = true,
    .named = true,
  },
  [sym_object_key] = {
    .visible = true,
    .named = true,
  },
  [sym_quoted_string] = {
    .visible = true,
    .named = true,
  },
  [sym_raw_string] = {
    .visible = true,
    .named = true,
  },
  [sym_quoted_bytes] = {
    .visible = true,
    .named = true,
  },
  [sym_raw_bytes] = {
    .visible = true,
    .named = true,
  },
  [sym_base64_bytes] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_object_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_array_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(35);
      ADVANCE_MAP(
        '"', 71,
        '\'', 44,
        '(', 36,
        ')', 37,
        ',', 39,
        '/', 6,
        '0', 91,
        ':', 55,
        '[', 41,
        ']', 42,
        '_', 32,
        'b', 56,
        'f', 59,
        'n', 68,
        'r', 73,
        't', 65,
        '{', 38,
        '}', 40,
        '+', 11,
        '-', 11,
      );
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(90);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(69);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(54);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '"', 71,
        '\'', 44,
        '(', 36,
        ')', 37,
        ',', 39,
        '/', 6,
        '0', 91,
        '[', 41,
        ']', 42,
        'b', 2,
        'f', 15,
        'n', 24,
        'r', 72,
        't', 21,
        '{', 38,
        '+', 11,
        '-', 11,
      );
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(1);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(90);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(54);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(74);
      if (lookahead == '6') ADVANCE(14);
      if (lookahead == 'r') ADVANCE(75);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(77);
      END_STATE();
    case 4:
      if (lookahead == '"') ADVANCE(70);
      if (lookahead == '/') ADVANCE(6);
      if (lookahead == '_') ADVANCE(32);
      if (lookahead == 'r') ADVANCE(73);
      if (lookahead == '}') ADVANCE(40);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(4);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(69);
      END_STATE();
    case 5:
      if (lookahead == '\'') ADVANCE(8);
      if (lookahead == '*') ADVANCE(86);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(5);
      if (lookahead != 0) ADVANCE(87);
      END_STATE();
    case 6:
      if (lookahead == '*') ADVANCE(8);
      if (lookahead == '/') ADVANCE(97);
      END_STATE();
    case 7:
      if (lookahead == '*') ADVANCE(7);
      if (lookahead == '/') ADVANCE(98);
      if (lookahead != 0) ADVANCE(8);
      END_STATE();
    case 8:
      if (lookahead == '*') ADVANCE(7);
      if (lookahead != 0) ADVANCE(8);
      END_STATE();
    case 9:
      if (lookahead == '*') ADVANCE(5);
      if (lookahead == '/') ADVANCE(96);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(26);
      END_STATE();
    case 10:
      if (lookahead == '/') ADVANCE(9);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(10);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(34);
      END_STATE();
    case 11:
      if (lookahead == '0') ADVANCE(92);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(90);
      END_STATE();
    case 12:
      if (lookahead == '0') ADVANCE(45);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(13);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(47);
      END_STATE();
    case 13:
      if (lookahead == '0') ADVANCE(45);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(47);
      END_STATE();
    case 14:
      if (lookahead == '4') ADVANCE(3);
      END_STATE();
    case 15:
      if (lookahead == 'a') ADVANCE(18);
      END_STATE();
    case 16:
      if (lookahead == 'e') ADVANCE(48);
      END_STATE();
    case 17:
      if (lookahead == 'e') ADVANCE(50);
      END_STATE();
    case 18:
      if (lookahead == 'l') ADVANCE(22);
      END_STATE();
    case 19:
      if (lookahead == 'l') ADVANCE(52);
      END_STATE();
    case 20:
      if (lookahead == 'l') ADVANCE(19);
      END_STATE();
    case 21:
      if (lookahead == 'r') ADVANCE(23);
      END_STATE();
    case 22:
      if (lookahead == 's') ADVANCE(17);
      END_STATE();
    case 23:
      if (lookahead == 'u') ADVANCE(16);
      END_STATE();
    case 24:
      if (lookahead == 'u') ADVANCE(20);
      END_STATE();
    case 25:
      if (lookahead == '0' ||
          lookahead == '1') ADVANCE(95);
      END_STATE();
    case 26:
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(26);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(89);
      END_STATE();
    case 27:
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(94);
      END_STATE();
    case 28:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(90);
      END_STATE();
    case 29:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(46);
      END_STATE();
    case 30:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(47);
      END_STATE();
    case 31:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(93);
      END_STATE();
    case 32:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(69);
      END_STATE();
    case 33:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      END_STATE();
    case 34:
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(26);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_DQUOTE_DQUOTE);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_float);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_float);
      if (lookahead == '_') ADVANCE(29);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(12);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(46);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_float);
      if (lookahead == '_') ADVANCE(30);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(47);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_true);
      if (lookahead == '-' ||
          lookahead == '_') ADVANCE(32);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(69);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_false);
      if (lookahead == '-' ||
          lookahead == '_') ADVANCE(32);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(69);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_null);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_null);
      if (lookahead == '-' ||
          lookahead == '_') ADVANCE(32);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(69);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '-' ||
          lookahead == '_') ADVANCE(33);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_plain_key);
      if (lookahead == '"') ADVANCE(74);
      if (lookahead == '6') ADVANCE(58);
      if (lookahead == 'r') ADVANCE(76);
      if (lookahead == '-' ||
          lookahead == '_') ADVANCE(32);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(69);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_plain_key);
      if (lookahead == '"') ADVANCE(77);
      if (lookahead == '-' ||
          lookahead == '_') ADVANCE(32);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(69);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_plain_key);
      if (lookahead == '4') ADVANCE(57);
      if (lookahead == '-' ||
          lookahead == '_') ADVANCE(32);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(69);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_plain_key);
      if (lookahead == 'a') ADVANCE(62);
      if (lookahead == '-' ||
          lookahead == '_') ADVANCE(32);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(69);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_plain_key);
      if (lookahead == 'e') ADVANCE(49);
      if (lookahead == '-' ||
          lookahead == '_') ADVANCE(32);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(69);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_plain_key);
      if (lookahead == 'e') ADVANCE(51);
      if (lookahead == '-' ||
          lookahead == '_') ADVANCE(32);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(69);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_plain_key);
      if (lookahead == 'l') ADVANCE(66);
      if (lookahead == '-' ||
          lookahead == '_') ADVANCE(32);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(69);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_plain_key);
      if (lookahead == 'l') ADVANCE(53);
      if (lookahead == '-' ||
          lookahead == '_') ADVANCE(32);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(69);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_plain_key);
      if (lookahead == 'l') ADVANCE(63);
      if (lookahead == '-' ||
          lookahead == '_') ADVANCE(32);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(69);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_plain_key);
      if (lookahead == 'r') ADVANCE(67);
      if (lookahead == '-' ||
          lookahead == '_') ADVANCE(32);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(69);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_plain_key);
      if (lookahead == 's') ADVANCE(61);
      if (lookahead == '-' ||
          lookahead == '_') ADVANCE(32);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(69);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_plain_key);
      if (lookahead == 'u') ADVANCE(60);
      if (lookahead == '-' ||
          lookahead == '_') ADVANCE(32);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(69);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_plain_key);
      if (lookahead == 'u') ADVANCE(64);
      if (lookahead == '-' ||
          lookahead == '_') ADVANCE(32);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(69);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_plain_key);
      if (lookahead == '-' ||
          lookahead == '_') ADVANCE(32);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(69);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      if (lookahead == '"') ADVANCE(43);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(anon_sym_r);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(anon_sym_r);
      if (lookahead == '-' ||
          lookahead == '_') ADVANCE(32);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(69);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(anon_sym_b_DQUOTE);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(anon_sym_br);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(anon_sym_br);
      if (lookahead == '-' ||
          lookahead == '_') ADVANCE(32);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(69);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(anon_sym_b64_DQUOTE);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym_base64_content);
      if (lookahead == '*') ADVANCE(8);
      if (lookahead == '/') ADVANCE(82);
      if (lookahead == '=') ADVANCE(81);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(80);
      if (lookahead == '+' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(80);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym_base64_content);
      if (lookahead == '/') ADVANCE(78);
      if (lookahead == '=') ADVANCE(81);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(79);
      if (lookahead == '+' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(80);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym_base64_content);
      if (lookahead == '=') ADVANCE(81);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(80);
      if (lookahead == '+' ||
          ('/' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(80);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym_base64_content);
      if (lookahead == '=') ADVANCE(85);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(81);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym_base64_content);
      if (lookahead == '=') ADVANCE(83);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(82);
      if (lookahead == '\n' ||
          lookahead == '\r') ADVANCE(80);
      if (lookahead == '+' ||
          ('/' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      if (lookahead != 0) ADVANCE(97);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(sym_base64_content);
      if (lookahead == '=') ADVANCE(84);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(83);
      if (lookahead == '\n' ||
          lookahead == '\r') ADVANCE(81);
      if (lookahead != 0) ADVANCE(97);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(sym_base64_content);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(84);
      if (lookahead == '\n' ||
          lookahead == '\r') ADVANCE(85);
      if (lookahead != 0) ADVANCE(97);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(sym_base64_content);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(85);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(sym_temporal_content);
      if (lookahead == '\'') ADVANCE(8);
      if (lookahead == '*') ADVANCE(86);
      if (lookahead == '/') ADVANCE(89);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(87);
      if (lookahead != 0) ADVANCE(87);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(sym_temporal_content);
      if (lookahead == '\'') ADVANCE(8);
      if (lookahead == '*') ADVANCE(86);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(87);
      if (lookahead != 0) ADVANCE(87);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(sym_temporal_content);
      if (lookahead == '\'') ADVANCE(97);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(88);
      if (lookahead == '\n' ||
          lookahead == '\r') ADVANCE(89);
      if (lookahead != 0) ADVANCE(88);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(sym_temporal_content);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(89);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(89);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(sym_decimal_integer);
      if (lookahead == '.') ADVANCE(29);
      if (lookahead == '_') ADVANCE(28);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(12);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(90);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(sym_decimal_integer);
      if (lookahead == '.') ADVANCE(29);
      if (lookahead == 'b') ADVANCE(25);
      if (lookahead == 'o') ADVANCE(27);
      if (lookahead == 'x') ADVANCE(31);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(12);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(sym_decimal_integer);
      if (lookahead == '.') ADVANCE(29);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(12);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(sym_hex_integer);
      if (lookahead == '_') ADVANCE(31);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(93);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(sym_octal_integer);
      if (lookahead == '_') ADVANCE(27);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(94);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(sym_binary_integer);
      if (lookahead == '_') ADVANCE(25);
      if (lookahead == '0' ||
          lookahead == '1') ADVANCE(95);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(sym_line_comment);
      if (lookahead == '\'') ADVANCE(97);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(96);
      if (lookahead == '\n' ||
          lookahead == '\r') ADVANCE(26);
      if (lookahead != 0) ADVANCE(88);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(sym_line_comment);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(97);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(sym_block_comment);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 1},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 1},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 1},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 4},
  [12] = {.lex_state = 4},
  [13] = {.lex_state = 4},
  [14] = {.lex_state = 4},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0, .external_lex_state = 2},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0, .external_lex_state = 3},
  [55] = {.lex_state = 0, .external_lex_state = 4},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0, .external_lex_state = 4},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0, .external_lex_state = 2},
  [61] = {.lex_state = 0, .external_lex_state = 3},
  [62] = {.lex_state = 0, .external_lex_state = 5},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 79},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0, .external_lex_state = 5},
  [68] = {.lex_state = 10},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_DQUOTE_DQUOTE] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [sym_float] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [sym_null] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [sym_plain_key] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_r] = ACTIONS(1),
    [anon_sym_b_DQUOTE] = ACTIONS(1),
    [anon_sym_br] = ACTIONS(1),
    [anon_sym_b64_DQUOTE] = ACTIONS(1),
    [sym_decimal_integer] = ACTIONS(1),
    [sym_hex_integer] = ACTIONS(1),
    [sym_octal_integer] = ACTIONS(1),
    [sym_binary_integer] = ACTIONS(1),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
    [sym_raw_start] = ACTIONS(1),
    [sym_raw_content] = ACTIONS(1),
    [sym_raw_end] = ACTIONS(1),
    [sym_quoted_content] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_duper_value] = STATE(65),
    [sym_identified_value] = STATE(35),
    [sym__value] = STATE(35),
    [sym_object] = STATE(35),
    [sym_array] = STATE(35),
    [sym_tuple] = STATE(35),
    [sym_string] = STATE(35),
    [sym_bytes] = STATE(35),
    [sym_temporal] = STATE(35),
    [sym_integer] = STATE(35),
    [sym_boolean] = STATE(35),
    [sym_quoted_string] = STATE(21),
    [sym_raw_string] = STATE(21),
    [sym_quoted_bytes] = STATE(37),
    [sym_raw_bytes] = STATE(37),
    [sym_base64_bytes] = STATE(37),
    [anon_sym_LPAREN] = ACTIONS(5),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_LBRACK] = ACTIONS(9),
    [anon_sym_DQUOTE_DQUOTE] = ACTIONS(11),
    [anon_sym_SQUOTE] = ACTIONS(13),
    [sym_float] = ACTIONS(15),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [sym_null] = ACTIONS(15),
    [sym_identifier] = ACTIONS(19),
    [anon_sym_DQUOTE] = ACTIONS(21),
    [anon_sym_r] = ACTIONS(23),
    [anon_sym_b_DQUOTE] = ACTIONS(25),
    [anon_sym_br] = ACTIONS(27),
    [anon_sym_b64_DQUOTE] = ACTIONS(29),
    [sym_decimal_integer] = ACTIONS(31),
    [sym_hex_integer] = ACTIONS(33),
    [sym_octal_integer] = ACTIONS(33),
    [sym_binary_integer] = ACTIONS(33),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
  [STATE(2)] = {
    [sym_duper_value] = STATE(42),
    [sym_identified_value] = STATE(35),
    [sym__value] = STATE(35),
    [sym_object] = STATE(35),
    [sym_array] = STATE(35),
    [sym_tuple] = STATE(35),
    [sym_string] = STATE(35),
    [sym_bytes] = STATE(35),
    [sym_temporal] = STATE(35),
    [sym_integer] = STATE(35),
    [sym_boolean] = STATE(35),
    [sym_quoted_string] = STATE(21),
    [sym_raw_string] = STATE(21),
    [sym_quoted_bytes] = STATE(37),
    [sym_raw_bytes] = STATE(37),
    [sym_base64_bytes] = STATE(37),
    [anon_sym_LPAREN] = ACTIONS(5),
    [anon_sym_RPAREN] = ACTIONS(35),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_COMMA] = ACTIONS(37),
    [anon_sym_LBRACK] = ACTIONS(9),
    [anon_sym_DQUOTE_DQUOTE] = ACTIONS(11),
    [anon_sym_SQUOTE] = ACTIONS(13),
    [sym_float] = ACTIONS(15),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [sym_null] = ACTIONS(15),
    [sym_identifier] = ACTIONS(19),
    [anon_sym_DQUOTE] = ACTIONS(21),
    [anon_sym_r] = ACTIONS(23),
    [anon_sym_b_DQUOTE] = ACTIONS(25),
    [anon_sym_br] = ACTIONS(27),
    [anon_sym_b64_DQUOTE] = ACTIONS(29),
    [sym_decimal_integer] = ACTIONS(31),
    [sym_hex_integer] = ACTIONS(33),
    [sym_octal_integer] = ACTIONS(33),
    [sym_binary_integer] = ACTIONS(33),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
  [STATE(3)] = {
    [sym_duper_value] = STATE(43),
    [sym_identified_value] = STATE(35),
    [sym__value] = STATE(35),
    [sym_object] = STATE(35),
    [sym_array] = STATE(35),
    [sym_tuple] = STATE(35),
    [sym_string] = STATE(35),
    [sym_bytes] = STATE(35),
    [sym_temporal] = STATE(35),
    [sym_integer] = STATE(35),
    [sym_boolean] = STATE(35),
    [sym_quoted_string] = STATE(21),
    [sym_raw_string] = STATE(21),
    [sym_quoted_bytes] = STATE(37),
    [sym_raw_bytes] = STATE(37),
    [sym_base64_bytes] = STATE(37),
    [anon_sym_LPAREN] = ACTIONS(5),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_COMMA] = ACTIONS(39),
    [anon_sym_LBRACK] = ACTIONS(9),
    [anon_sym_RBRACK] = ACTIONS(41),
    [anon_sym_DQUOTE_DQUOTE] = ACTIONS(11),
    [anon_sym_SQUOTE] = ACTIONS(13),
    [sym_float] = ACTIONS(15),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [sym_null] = ACTIONS(15),
    [sym_identifier] = ACTIONS(19),
    [anon_sym_DQUOTE] = ACTIONS(21),
    [anon_sym_r] = ACTIONS(23),
    [anon_sym_b_DQUOTE] = ACTIONS(25),
    [anon_sym_br] = ACTIONS(27),
    [anon_sym_b64_DQUOTE] = ACTIONS(29),
    [sym_decimal_integer] = ACTIONS(31),
    [sym_hex_integer] = ACTIONS(33),
    [sym_octal_integer] = ACTIONS(33),
    [sym_binary_integer] = ACTIONS(33),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
  [STATE(4)] = {
    [sym_duper_value] = STATE(44),
    [sym_identified_value] = STATE(35),
    [sym__value] = STATE(35),
    [sym_object] = STATE(35),
    [sym_array] = STATE(35),
    [sym_tuple] = STATE(35),
    [sym_string] = STATE(35),
    [sym_bytes] = STATE(35),
    [sym_temporal] = STATE(35),
    [sym_integer] = STATE(35),
    [sym_boolean] = STATE(35),
    [sym_quoted_string] = STATE(21),
    [sym_raw_string] = STATE(21),
    [sym_quoted_bytes] = STATE(37),
    [sym_raw_bytes] = STATE(37),
    [sym_base64_bytes] = STATE(37),
    [anon_sym_LPAREN] = ACTIONS(5),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_LBRACK] = ACTIONS(9),
    [anon_sym_RBRACK] = ACTIONS(43),
    [anon_sym_DQUOTE_DQUOTE] = ACTIONS(11),
    [anon_sym_SQUOTE] = ACTIONS(13),
    [sym_float] = ACTIONS(15),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [sym_null] = ACTIONS(15),
    [sym_identifier] = ACTIONS(19),
    [anon_sym_DQUOTE] = ACTIONS(21),
    [anon_sym_r] = ACTIONS(23),
    [anon_sym_b_DQUOTE] = ACTIONS(25),
    [anon_sym_br] = ACTIONS(27),
    [anon_sym_b64_DQUOTE] = ACTIONS(29),
    [sym_decimal_integer] = ACTIONS(31),
    [sym_hex_integer] = ACTIONS(33),
    [sym_octal_integer] = ACTIONS(33),
    [sym_binary_integer] = ACTIONS(33),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
  [STATE(5)] = {
    [sym_duper_value] = STATE(44),
    [sym_identified_value] = STATE(35),
    [sym__value] = STATE(35),
    [sym_object] = STATE(35),
    [sym_array] = STATE(35),
    [sym_tuple] = STATE(35),
    [sym_string] = STATE(35),
    [sym_bytes] = STATE(35),
    [sym_temporal] = STATE(35),
    [sym_integer] = STATE(35),
    [sym_boolean] = STATE(35),
    [sym_quoted_string] = STATE(21),
    [sym_raw_string] = STATE(21),
    [sym_quoted_bytes] = STATE(37),
    [sym_raw_bytes] = STATE(37),
    [sym_base64_bytes] = STATE(37),
    [anon_sym_LPAREN] = ACTIONS(5),
    [anon_sym_RPAREN] = ACTIONS(45),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_LBRACK] = ACTIONS(9),
    [anon_sym_DQUOTE_DQUOTE] = ACTIONS(11),
    [anon_sym_SQUOTE] = ACTIONS(13),
    [sym_float] = ACTIONS(15),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [sym_null] = ACTIONS(15),
    [sym_identifier] = ACTIONS(19),
    [anon_sym_DQUOTE] = ACTIONS(21),
    [anon_sym_r] = ACTIONS(23),
    [anon_sym_b_DQUOTE] = ACTIONS(25),
    [anon_sym_br] = ACTIONS(27),
    [anon_sym_b64_DQUOTE] = ACTIONS(29),
    [sym_decimal_integer] = ACTIONS(31),
    [sym_hex_integer] = ACTIONS(33),
    [sym_octal_integer] = ACTIONS(33),
    [sym_binary_integer] = ACTIONS(33),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
  [STATE(6)] = {
    [sym_duper_value] = STATE(44),
    [sym_identified_value] = STATE(35),
    [sym__value] = STATE(35),
    [sym_object] = STATE(35),
    [sym_array] = STATE(35),
    [sym_tuple] = STATE(35),
    [sym_string] = STATE(35),
    [sym_bytes] = STATE(35),
    [sym_temporal] = STATE(35),
    [sym_integer] = STATE(35),
    [sym_boolean] = STATE(35),
    [sym_quoted_string] = STATE(21),
    [sym_raw_string] = STATE(21),
    [sym_quoted_bytes] = STATE(37),
    [sym_raw_bytes] = STATE(37),
    [sym_base64_bytes] = STATE(37),
    [anon_sym_LPAREN] = ACTIONS(5),
    [anon_sym_RPAREN] = ACTIONS(47),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_LBRACK] = ACTIONS(9),
    [anon_sym_DQUOTE_DQUOTE] = ACTIONS(11),
    [anon_sym_SQUOTE] = ACTIONS(13),
    [sym_float] = ACTIONS(15),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [sym_null] = ACTIONS(15),
    [sym_identifier] = ACTIONS(19),
    [anon_sym_DQUOTE] = ACTIONS(21),
    [anon_sym_r] = ACTIONS(23),
    [anon_sym_b_DQUOTE] = ACTIONS(25),
    [anon_sym_br] = ACTIONS(27),
    [anon_sym_b64_DQUOTE] = ACTIONS(29),
    [sym_decimal_integer] = ACTIONS(31),
    [sym_hex_integer] = ACTIONS(33),
    [sym_octal_integer] = ACTIONS(33),
    [sym_binary_integer] = ACTIONS(33),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
  [STATE(7)] = {
    [sym_duper_value] = STATE(44),
    [sym_identified_value] = STATE(35),
    [sym__value] = STATE(35),
    [sym_object] = STATE(35),
    [sym_array] = STATE(35),
    [sym_tuple] = STATE(35),
    [sym_string] = STATE(35),
    [sym_bytes] = STATE(35),
    [sym_temporal] = STATE(35),
    [sym_integer] = STATE(35),
    [sym_boolean] = STATE(35),
    [sym_quoted_string] = STATE(21),
    [sym_raw_string] = STATE(21),
    [sym_quoted_bytes] = STATE(37),
    [sym_raw_bytes] = STATE(37),
    [sym_base64_bytes] = STATE(37),
    [anon_sym_LPAREN] = ACTIONS(5),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_LBRACK] = ACTIONS(9),
    [anon_sym_RBRACK] = ACTIONS(49),
    [anon_sym_DQUOTE_DQUOTE] = ACTIONS(11),
    [anon_sym_SQUOTE] = ACTIONS(13),
    [sym_float] = ACTIONS(15),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [sym_null] = ACTIONS(15),
    [sym_identifier] = ACTIONS(19),
    [anon_sym_DQUOTE] = ACTIONS(21),
    [anon_sym_r] = ACTIONS(23),
    [anon_sym_b_DQUOTE] = ACTIONS(25),
    [anon_sym_br] = ACTIONS(27),
    [anon_sym_b64_DQUOTE] = ACTIONS(29),
    [sym_decimal_integer] = ACTIONS(31),
    [sym_hex_integer] = ACTIONS(33),
    [sym_octal_integer] = ACTIONS(33),
    [sym_binary_integer] = ACTIONS(33),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
  [STATE(8)] = {
    [sym_duper_value] = STATE(49),
    [sym_identified_value] = STATE(35),
    [sym__value] = STATE(35),
    [sym_object] = STATE(35),
    [sym_array] = STATE(35),
    [sym_tuple] = STATE(35),
    [sym_string] = STATE(35),
    [sym_bytes] = STATE(35),
    [sym_temporal] = STATE(35),
    [sym_integer] = STATE(35),
    [sym_boolean] = STATE(35),
    [sym_quoted_string] = STATE(21),
    [sym_raw_string] = STATE(21),
    [sym_quoted_bytes] = STATE(37),
    [sym_raw_bytes] = STATE(37),
    [sym_base64_bytes] = STATE(37),
    [anon_sym_LPAREN] = ACTIONS(5),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_LBRACK] = ACTIONS(9),
    [anon_sym_DQUOTE_DQUOTE] = ACTIONS(11),
    [anon_sym_SQUOTE] = ACTIONS(13),
    [sym_float] = ACTIONS(15),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [sym_null] = ACTIONS(15),
    [sym_identifier] = ACTIONS(19),
    [anon_sym_DQUOTE] = ACTIONS(21),
    [anon_sym_r] = ACTIONS(23),
    [anon_sym_b_DQUOTE] = ACTIONS(25),
    [anon_sym_br] = ACTIONS(27),
    [anon_sym_b64_DQUOTE] = ACTIONS(29),
    [sym_decimal_integer] = ACTIONS(31),
    [sym_hex_integer] = ACTIONS(33),
    [sym_octal_integer] = ACTIONS(33),
    [sym_binary_integer] = ACTIONS(33),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
  [STATE(9)] = {
    [sym_duper_value] = STATE(44),
    [sym_identified_value] = STATE(35),
    [sym__value] = STATE(35),
    [sym_object] = STATE(35),
    [sym_array] = STATE(35),
    [sym_tuple] = STATE(35),
    [sym_string] = STATE(35),
    [sym_bytes] = STATE(35),
    [sym_temporal] = STATE(35),
    [sym_integer] = STATE(35),
    [sym_boolean] = STATE(35),
    [sym_quoted_string] = STATE(21),
    [sym_raw_string] = STATE(21),
    [sym_quoted_bytes] = STATE(37),
    [sym_raw_bytes] = STATE(37),
    [sym_base64_bytes] = STATE(37),
    [anon_sym_LPAREN] = ACTIONS(5),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_LBRACK] = ACTIONS(9),
    [anon_sym_DQUOTE_DQUOTE] = ACTIONS(11),
    [anon_sym_SQUOTE] = ACTIONS(13),
    [sym_float] = ACTIONS(15),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [sym_null] = ACTIONS(15),
    [sym_identifier] = ACTIONS(19),
    [anon_sym_DQUOTE] = ACTIONS(21),
    [anon_sym_r] = ACTIONS(23),
    [anon_sym_b_DQUOTE] = ACTIONS(25),
    [anon_sym_br] = ACTIONS(27),
    [anon_sym_b64_DQUOTE] = ACTIONS(29),
    [sym_decimal_integer] = ACTIONS(31),
    [sym_hex_integer] = ACTIONS(33),
    [sym_octal_integer] = ACTIONS(33),
    [sym_binary_integer] = ACTIONS(33),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
  [STATE(10)] = {
    [sym__value] = STATE(53),
    [sym_object] = STATE(53),
    [sym_array] = STATE(53),
    [sym_tuple] = STATE(53),
    [sym_string] = STATE(53),
    [sym_bytes] = STATE(53),
    [sym_temporal] = STATE(53),
    [sym_integer] = STATE(53),
    [sym_boolean] = STATE(53),
    [sym_quoted_string] = STATE(21),
    [sym_raw_string] = STATE(21),
    [sym_quoted_bytes] = STATE(37),
    [sym_raw_bytes] = STATE(37),
    [sym_base64_bytes] = STATE(37),
    [anon_sym_LPAREN] = ACTIONS(5),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_LBRACK] = ACTIONS(9),
    [anon_sym_DQUOTE_DQUOTE] = ACTIONS(11),
    [anon_sym_SQUOTE] = ACTIONS(13),
    [sym_float] = ACTIONS(51),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [sym_null] = ACTIONS(51),
    [anon_sym_DQUOTE] = ACTIONS(21),
    [anon_sym_r] = ACTIONS(23),
    [anon_sym_b_DQUOTE] = ACTIONS(25),
    [anon_sym_br] = ACTIONS(27),
    [anon_sym_b64_DQUOTE] = ACTIONS(29),
    [sym_decimal_integer] = ACTIONS(31),
    [sym_hex_integer] = ACTIONS(33),
    [sym_octal_integer] = ACTIONS(33),
    [sym_binary_integer] = ACTIONS(33),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 8,
    ACTIONS(53), 1,
      anon_sym_RBRACE,
    ACTIONS(55), 1,
      sym_plain_key,
    ACTIONS(57), 1,
      anon_sym_DQUOTE,
    ACTIONS(59), 1,
      anon_sym_r,
    STATE(48), 1,
      sym_object_entry,
    STATE(69), 1,
      sym_object_key,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(58), 2,
      sym_quoted_string,
      sym_raw_string,
  [27] = 8,
    ACTIONS(55), 1,
      sym_plain_key,
    ACTIONS(57), 1,
      anon_sym_DQUOTE,
    ACTIONS(59), 1,
      anon_sym_r,
    ACTIONS(61), 1,
      anon_sym_RBRACE,
    STATE(48), 1,
      sym_object_entry,
    STATE(69), 1,
      sym_object_key,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(58), 2,
      sym_quoted_string,
      sym_raw_string,
  [54] = 8,
    ACTIONS(55), 1,
      sym_plain_key,
    ACTIONS(57), 1,
      anon_sym_DQUOTE,
    ACTIONS(59), 1,
      anon_sym_r,
    ACTIONS(63), 1,
      anon_sym_RBRACE,
    STATE(45), 1,
      sym_object_entry,
    STATE(69), 1,
      sym_object_key,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(58), 2,
      sym_quoted_string,
      sym_raw_string,
  [81] = 7,
    ACTIONS(55), 1,
      sym_plain_key,
    ACTIONS(57), 1,
      anon_sym_DQUOTE,
    ACTIONS(59), 1,
      anon_sym_r,
    STATE(48), 1,
      sym_object_entry,
    STATE(69), 1,
      sym_object_key,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(58), 2,
      sym_quoted_string,
      sym_raw_string,
  [105] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(65), 6,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      anon_sym_COLON,
  [118] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(67), 6,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      anon_sym_COLON,
  [131] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(69), 5,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
  [143] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(71), 5,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
  [155] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(73), 5,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
  [167] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(75), 5,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
  [179] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(77), 5,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
  [191] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(79), 5,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
  [203] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(81), 5,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
  [215] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(83), 5,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
  [227] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(85), 5,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
  [239] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(87), 5,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
  [251] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(89), 5,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
  [263] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(91), 5,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
  [275] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(93), 5,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
  [287] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(95), 5,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
  [299] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(97), 5,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
  [311] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(99), 5,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
  [323] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(101), 5,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
  [335] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(103), 5,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
  [347] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(105), 5,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
  [359] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(107), 5,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
  [371] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(109), 5,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
  [383] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(111), 5,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
  [395] = 4,
    ACTIONS(115), 1,
      anon_sym_COMMA,
    STATE(39), 1,
      aux_sym_array_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(113), 2,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [410] = 4,
    ACTIONS(43), 1,
      anon_sym_RBRACK,
    ACTIONS(118), 1,
      anon_sym_COMMA,
    STATE(39), 1,
      aux_sym_array_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [424] = 4,
    ACTIONS(53), 1,
      anon_sym_RBRACE,
    ACTIONS(120), 1,
      anon_sym_COMMA,
    STATE(46), 1,
      aux_sym_object_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [438] = 4,
    ACTIONS(122), 1,
      anon_sym_RPAREN,
    ACTIONS(124), 1,
      anon_sym_COMMA,
    STATE(47), 1,
      aux_sym_array_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [452] = 4,
    ACTIONS(126), 1,
      anon_sym_COMMA,
    ACTIONS(128), 1,
      anon_sym_RBRACK,
    STATE(40), 1,
      aux_sym_array_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [466] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(113), 3,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [476] = 4,
    ACTIONS(130), 1,
      anon_sym_COMMA,
    ACTIONS(132), 1,
      anon_sym_RBRACE,
    STATE(41), 1,
      aux_sym_object_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [490] = 4,
    ACTIONS(134), 1,
      anon_sym_COMMA,
    ACTIONS(137), 1,
      anon_sym_RBRACE,
    STATE(46), 1,
      aux_sym_object_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [504] = 4,
    ACTIONS(45), 1,
      anon_sym_RPAREN,
    ACTIONS(139), 1,
      anon_sym_COMMA,
    STATE(39), 1,
      aux_sym_array_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [518] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(137), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [527] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(141), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [536] = 2,
    ACTIONS(143), 1,
      sym_quoted_content,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [544] = 2,
    ACTIONS(122), 1,
      anon_sym_RPAREN,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [552] = 2,
    ACTIONS(145), 1,
      anon_sym_LPAREN,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [560] = 2,
    ACTIONS(147), 1,
      anon_sym_RPAREN,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [568] = 2,
    ACTIONS(149), 1,
      sym_raw_start,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [576] = 2,
    ACTIONS(151), 1,
      sym_raw_end,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [584] = 2,
    ACTIONS(153), 1,
      anon_sym_SQUOTE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [592] = 2,
    ACTIONS(155), 1,
      sym_raw_end,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [600] = 2,
    ACTIONS(157), 1,
      anon_sym_COLON,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [608] = 2,
    ACTIONS(159), 1,
      anon_sym_DQUOTE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [616] = 2,
    ACTIONS(161), 1,
      sym_quoted_content,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [624] = 2,
    ACTIONS(163), 1,
      sym_raw_start,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [632] = 2,
    ACTIONS(165), 1,
      sym_raw_content,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [640] = 2,
    ACTIONS(167), 1,
      anon_sym_DQUOTE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [648] = 2,
    ACTIONS(169), 1,
      sym_base64_content,
    ACTIONS(171), 2,
      sym_line_comment,
      sym_block_comment,
  [656] = 2,
    ACTIONS(173), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [664] = 2,
    ACTIONS(175), 1,
      anon_sym_DQUOTE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [672] = 2,
    ACTIONS(177), 1,
      sym_raw_content,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [680] = 2,
    ACTIONS(179), 1,
      sym_temporal_content,
    ACTIONS(171), 2,
      sym_line_comment,
      sym_block_comment,
  [688] = 2,
    ACTIONS(181), 1,
      anon_sym_COLON,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [696] = 2,
    ACTIONS(128), 1,
      anon_sym_RBRACK,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(11)] = 0,
  [SMALL_STATE(12)] = 27,
  [SMALL_STATE(13)] = 54,
  [SMALL_STATE(14)] = 81,
  [SMALL_STATE(15)] = 105,
  [SMALL_STATE(16)] = 118,
  [SMALL_STATE(17)] = 131,
  [SMALL_STATE(18)] = 143,
  [SMALL_STATE(19)] = 155,
  [SMALL_STATE(20)] = 167,
  [SMALL_STATE(21)] = 179,
  [SMALL_STATE(22)] = 191,
  [SMALL_STATE(23)] = 203,
  [SMALL_STATE(24)] = 215,
  [SMALL_STATE(25)] = 227,
  [SMALL_STATE(26)] = 239,
  [SMALL_STATE(27)] = 251,
  [SMALL_STATE(28)] = 263,
  [SMALL_STATE(29)] = 275,
  [SMALL_STATE(30)] = 287,
  [SMALL_STATE(31)] = 299,
  [SMALL_STATE(32)] = 311,
  [SMALL_STATE(33)] = 323,
  [SMALL_STATE(34)] = 335,
  [SMALL_STATE(35)] = 347,
  [SMALL_STATE(36)] = 359,
  [SMALL_STATE(37)] = 371,
  [SMALL_STATE(38)] = 383,
  [SMALL_STATE(39)] = 395,
  [SMALL_STATE(40)] = 410,
  [SMALL_STATE(41)] = 424,
  [SMALL_STATE(42)] = 438,
  [SMALL_STATE(43)] = 452,
  [SMALL_STATE(44)] = 466,
  [SMALL_STATE(45)] = 476,
  [SMALL_STATE(46)] = 490,
  [SMALL_STATE(47)] = 504,
  [SMALL_STATE(48)] = 518,
  [SMALL_STATE(49)] = 527,
  [SMALL_STATE(50)] = 536,
  [SMALL_STATE(51)] = 544,
  [SMALL_STATE(52)] = 552,
  [SMALL_STATE(53)] = 560,
  [SMALL_STATE(54)] = 568,
  [SMALL_STATE(55)] = 576,
  [SMALL_STATE(56)] = 584,
  [SMALL_STATE(57)] = 592,
  [SMALL_STATE(58)] = 600,
  [SMALL_STATE(59)] = 608,
  [SMALL_STATE(60)] = 616,
  [SMALL_STATE(61)] = 624,
  [SMALL_STATE(62)] = 632,
  [SMALL_STATE(63)] = 640,
  [SMALL_STATE(64)] = 648,
  [SMALL_STATE(65)] = 656,
  [SMALL_STATE(66)] = 664,
  [SMALL_STATE(67)] = 672,
  [SMALL_STATE(68)] = 680,
  [SMALL_STATE(69)] = 688,
  [SMALL_STATE(70)] = 696,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(50),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [55] = {.entry = {.count = 1, .reusable = false}}, SHIFT(58),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [59] = {.entry = {.count = 1, .reusable = false}}, SHIFT(54),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_string, 3, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_raw_string, 4, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object, 4, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 5, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object, 2, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 2, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 1, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tuple, 3, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object, 3, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 3, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_temporal, 3, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_bytes, 3, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_base64_bytes, 3, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tuple, 4, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 4, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_integer, 1, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_identified_value, 4, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_raw_bytes, 4, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tuple, 5, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_duper_value, 1, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object, 5, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bytes, 1, 0, 0),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tuple, 2, 0, 0),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0),
  [115] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [134] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_object_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_object_repeat1, 2, 0, 0),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object_entry, 3, 0, 0),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [149] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object_key, 1, 0, 0),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [169] = {.entry = {.count = 1, .reusable = false}}, SHIFT(66),
  [171] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [173] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [179] = {.entry = {.count = 1, .reusable = false}}, SHIFT(56),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token_raw_start = 0,
  ts_external_token_raw_content = 1,
  ts_external_token_raw_end = 2,
  ts_external_token_quoted_content = 3,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token_raw_start] = sym_raw_start,
  [ts_external_token_raw_content] = sym_raw_content,
  [ts_external_token_raw_end] = sym_raw_end,
  [ts_external_token_quoted_content] = sym_quoted_content,
};

static const bool ts_external_scanner_states[6][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token_raw_start] = true,
    [ts_external_token_raw_content] = true,
    [ts_external_token_raw_end] = true,
    [ts_external_token_quoted_content] = true,
  },
  [2] = {
    [ts_external_token_quoted_content] = true,
  },
  [3] = {
    [ts_external_token_raw_start] = true,
  },
  [4] = {
    [ts_external_token_raw_end] = true,
  },
  [5] = {
    [ts_external_token_raw_content] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_duper_external_scanner_create(void);
void tree_sitter_duper_external_scanner_destroy(void *);
bool tree_sitter_duper_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_duper_external_scanner_serialize(void *, char *);
void tree_sitter_duper_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_duper(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_duper_external_scanner_create,
      tree_sitter_duper_external_scanner_destroy,
      tree_sitter_duper_external_scanner_scan,
      tree_sitter_duper_external_scanner_serialize,
      tree_sitter_duper_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
    .name = "duper",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 1,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
