// <auto-generated>
//     This file was generated by uniffi-bindgen-cs v0.10.0+v0.29.4
//     See https://github.com/NordSecurity/uniffi-bindgen-cs for more information.
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.InteropServices;

namespace Duper.Ffi;

// This is a helper for safely working with byte buffers returned from the Rust code.
// A rust-owned buffer is represented by its capacity, its current length, and a
// pointer to the underlying data.

[StructLayout(LayoutKind.Sequential)]
internal struct RustBuffer
{
    public ulong capacity;
    public ulong len;
    public IntPtr data;

    public static RustBuffer Alloc(int size)
    {
        return _UniffiHelpers.RustCall(
            (ref UniffiRustCallStatus status) =>
            {
                var buffer = _UniFFILib.ffi_duper_uniffi_rustbuffer_alloc(
                    Convert.ToUInt64(size),
                    ref status
                );
                if (buffer.data == IntPtr.Zero)
                {
                    throw new AllocationException(
                        $"RustBuffer.Alloc() returned null data pointer (size={size})"
                    );
                }
                return buffer;
            }
        );
    }

    public static void Free(RustBuffer buffer)
    {
        _UniffiHelpers.RustCall(
            (ref UniffiRustCallStatus status) =>
            {
                _UniFFILib.ffi_duper_uniffi_rustbuffer_free(buffer, ref status);
            }
        );
    }

    public static BigEndianStream MemoryStream(IntPtr data, long length)
    {
        unsafe
        {
            return new BigEndianStream(new UnmanagedMemoryStream((byte*)data.ToPointer(), length));
        }
    }

    public BigEndianStream AsStream()
    {
        unsafe
        {
            return new BigEndianStream(
                new UnmanagedMemoryStream((byte*)data.ToPointer(), Convert.ToInt64(len))
            );
        }
    }

    public BigEndianStream AsWriteableStream()
    {
        unsafe
        {
            return new BigEndianStream(
                new UnmanagedMemoryStream(
                    (byte*)data.ToPointer(),
                    Convert.ToInt64(capacity),
                    Convert.ToInt64(capacity),
                    FileAccess.Write
                )
            );
        }
    }
}

// This is a helper for safely passing byte references into the rust code.
// It's not actually used at the moment, because there aren't many things that you
// can take a direct pointer to managed memory, and if we're going to copy something
// then we might as well copy it into a `RustBuffer`. But it's here for API
// completeness.

[StructLayout(LayoutKind.Sequential)]
internal struct ForeignBytes
{
    public int length;
    public IntPtr data;
}

// The FfiConverter interface handles converter types to and from the FFI
//
// All implementing objects should be public to support external types.  When a
// type is external we need to import it's FfiConverter.
internal abstract class FfiConverter<CsType, FfiType>
{
    // Convert an FFI type to a C# type
    public abstract CsType Lift(FfiType value);

    // Convert C# type to an FFI type
    public abstract FfiType Lower(CsType value);

    // Read a C# type from a `ByteBuffer`
    public abstract CsType Read(BigEndianStream stream);

    // Calculate bytes to allocate when creating a `RustBuffer`
    //
    // This must return at least as many bytes as the write() function will
    // write. It can return more bytes than needed, for example when writing
    // Strings we can't know the exact bytes needed until we the UTF-8
    // encoding, so we pessimistically allocate the largest size possible (3
    // bytes per codepoint).  Allocating extra bytes is not really a big deal
    // because the `RustBuffer` is short-lived.
    public abstract int AllocationSize(CsType value);

    // Write a C# type to a `ByteBuffer`
    public abstract void Write(CsType value, BigEndianStream stream);

    // Lower a value into a `RustBuffer`
    //
    // This method lowers a value into a `RustBuffer` rather than the normal
    // FfiType.  It's used by the callback interface code.  Callback interface
    // returns are always serialized into a `RustBuffer` regardless of their
    // normal FFI type.
    public RustBuffer LowerIntoRustBuffer(CsType value)
    {
        var rbuf = RustBuffer.Alloc(AllocationSize(value));
        try
        {
            var stream = rbuf.AsWriteableStream();
            Write(value, stream);
            rbuf.len = Convert.ToUInt64(stream.Position);
            return rbuf;
        }
        catch
        {
            RustBuffer.Free(rbuf);
            throw;
        }
    }

    // Lift a value from a `RustBuffer`.
    //
    // This here mostly because of the symmetry with `lowerIntoRustBuffer()`.
    // It's currently only used by the `FfiConverterRustBuffer` class below.
    protected CsType LiftFromRustBuffer(RustBuffer rbuf)
    {
        var stream = rbuf.AsStream();
        try
        {
            var item = Read(stream);
            if (stream.HasRemaining())
            {
                throw new InternalException(
                    "junk remaining in buffer after lifting, something is very wrong!!"
                );
            }
            return item;
        }
        finally
        {
            RustBuffer.Free(rbuf);
        }
    }
}

// FfiConverter that uses `RustBuffer` as the FfiType
internal abstract class FfiConverterRustBuffer<CsType> : FfiConverter<CsType, RustBuffer>
{
    public override CsType Lift(RustBuffer value)
    {
        return LiftFromRustBuffer(value);
    }

    public override RustBuffer Lower(CsType value)
    {
        return LowerIntoRustBuffer(value);
    }
}

// A handful of classes and functions to support the generated data structures.
// This would be a good candidate for isolating in its own ffi-support lib.
// Error runtime.
[StructLayout(LayoutKind.Sequential)]
struct UniffiRustCallStatus
{
    public sbyte code;
    public RustBuffer error_buf;

    public bool IsSuccess()
    {
        return code == 0;
    }

    public bool IsError()
    {
        return code == 1;
    }

    public bool IsPanic()
    {
        return code == 2;
    }
}

// Base class for all uniffi exceptions
internal class UniffiException : System.Exception
{
    public UniffiException()
        : base() { }

    public UniffiException(string message)
        : base(message) { }
}

internal class UndeclaredErrorException : UniffiException
{
    public UndeclaredErrorException(string message)
        : base(message) { }
}

internal class PanicException : UniffiException
{
    public PanicException(string message)
        : base(message) { }
}

internal class AllocationException : UniffiException
{
    public AllocationException(string message)
        : base(message) { }
}

internal class InternalException : UniffiException
{
    public InternalException(string message)
        : base(message) { }
}

internal class InvalidEnumException : InternalException
{
    public InvalidEnumException(string message)
        : base(message) { }
}

internal class UniffiContractVersionException : UniffiException
{
    public UniffiContractVersionException(string message)
        : base(message) { }
}

internal class UniffiContractChecksumException : UniffiException
{
    public UniffiContractChecksumException(string message)
        : base(message) { }
}

// Each top-level error class has a companion object that can lift the error from the call status's rust buffer
interface CallStatusErrorHandler<E>
    where E : System.Exception
{
    E Lift(RustBuffer error_buf);
}

// CallStatusErrorHandler implementation for times when we don't expect a CALL_ERROR
class NullCallStatusErrorHandler : CallStatusErrorHandler<UniffiException>
{
    public static NullCallStatusErrorHandler INSTANCE = new NullCallStatusErrorHandler();

    public UniffiException Lift(RustBuffer error_buf)
    {
        RustBuffer.Free(error_buf);
        return new UndeclaredErrorException(
            "library has returned an error not declared in UNIFFI interface file"
        );
    }
}

// Helpers for calling Rust
// In practice we usually need to be synchronized to call this safely, so it doesn't
// synchronize itself
class _UniffiHelpers
{
    public delegate void RustCallAction(ref UniffiRustCallStatus status);
    public delegate U RustCallFunc<out U>(ref UniffiRustCallStatus status);

    // Call a rust function that returns a Result<>.  Pass in the Error class companion that corresponds to the Err
    public static U RustCallWithError<U, E>(
        CallStatusErrorHandler<E> errorHandler,
        RustCallFunc<U> callback
    )
        where E : UniffiException
    {
        var status = new UniffiRustCallStatus();
        var return_value = callback(ref status);
        if (status.IsSuccess())
        {
            return return_value;
        }
        else if (status.IsError())
        {
            throw errorHandler.Lift(status.error_buf);
        }
        else if (status.IsPanic())
        {
            // when the rust code sees a panic, it tries to construct a rustbuffer
            // with the message.  but if that code panics, then it just sends back
            // an empty buffer.
            if (status.error_buf.len > 0)
            {
                throw new PanicException(FfiConverterString.INSTANCE.Lift(status.error_buf));
            }
            else
            {
                throw new PanicException("Rust panic");
            }
        }
        else
        {
            throw new InternalException($"Unknown rust call status: {status.code}");
        }
    }

    // Call a rust function that returns a Result<>.  Pass in the Error class companion that corresponds to the Err
    public static void RustCallWithError<E>(
        CallStatusErrorHandler<E> errorHandler,
        RustCallAction callback
    )
        where E : UniffiException
    {
        _UniffiHelpers.RustCallWithError(
            errorHandler,
            (ref UniffiRustCallStatus status) =>
            {
                callback(ref status);
                return 0;
            }
        );
    }

    // Call a rust function that returns a plain value
    public static U RustCall<U>(RustCallFunc<U> callback)
    {
        return _UniffiHelpers.RustCallWithError(NullCallStatusErrorHandler.INSTANCE, callback);
    }

    // Call a rust function that returns a plain value
    public static void RustCall(RustCallAction callback)
    {
        _UniffiHelpers.RustCall(
            (ref UniffiRustCallStatus status) =>
            {
                callback(ref status);
                return 0;
            }
        );
    }
}

static class FFIObjectUtil
{
    public static void DisposeAll(params Object?[] list)
    {
        Dispose(list);
    }

    // Dispose is implemented by recursive type inspection at runtime. This is because
    // generating correct Dispose calls for recursive complex types, e.g. List<List<int>>
    // is quite cumbersome.
    private static void Dispose(Object? obj)
    {
        if (obj == null)
        {
            return;
        }

        if (obj is IDisposable disposable)
        {
            disposable.Dispose();
            return;
        }

        var objType = obj.GetType();
        var typeCode = Type.GetTypeCode(objType);
        if (typeCode != TypeCode.Object)
        {
            return;
        }

        var genericArguments = objType.GetGenericArguments();
        if (genericArguments.Length == 0 && !objType.IsArray)
        {
            return;
        }

        if (obj is System.Collections.IDictionary objDictionary)
        {
            //This extra code tests to not call "Dispose" for a Dictionary<something, double>()
            //for all values as "double" and alike doesn't support interface "IDisposable"
            var valuesType = objType.GetGenericArguments()[1];
            var elementValuesTypeCode = Type.GetTypeCode(valuesType);
            if (elementValuesTypeCode != TypeCode.Object)
            {
                return;
            }
            foreach (var value in objDictionary.Values)
            {
                Dispose(value);
            }
        }
        else if (obj is System.Collections.IEnumerable listValues)
        {
            //This extra code tests to not call "Dispose" for a List<int>()
            //for all keys as "int" and alike doesn't support interface "IDisposable"
            var elementType = objType.IsArray ? objType.GetElementType() : genericArguments[0];
            var elementValuesTypeCode = Type.GetTypeCode(elementType);
            if (elementValuesTypeCode != TypeCode.Object)
            {
                return;
            }
            foreach (var value in listValues)
            {
                Dispose(value);
            }
        }
    }
}

// Big endian streams are not yet available in dotnet :'(
// https://github.com/dotnet/runtime/issues/26904

class StreamUnderflowException : System.Exception
{
    public StreamUnderflowException() { }
}

static class BigEndianStreamExtensions
{
    public static void WriteInt32(this Stream stream, int value, int bytesToWrite = 4)
    {
#if DOTNET_8_0_OR_GREATER
        Span<byte> buffer = stackalloc byte[bytesToWrite];
#else
        byte[] buffer = new byte[bytesToWrite];
#endif
        var posByte = bytesToWrite;
        while (posByte != 0)
        {
            posByte--;
            buffer[posByte] = (byte)(value);
            value >>= 8;
        }

#if DOTNET_8_0_OR_GREATER
        stream.Write(buffer);
#else
        stream.Write(buffer, 0, buffer.Length);
#endif
    }

    public static void WriteInt64(this Stream stream, long value)
    {
        int bytesToWrite = 8;
#if DOTNET_8_0_OR_GREATER
        Span<byte> buffer = stackalloc byte[bytesToWrite];
#else
        byte[] buffer = new byte[bytesToWrite];
#endif
        var posByte = bytesToWrite;
        while (posByte != 0)
        {
            posByte--;
            buffer[posByte] = (byte)(value);
            value >>= 8;
        }

#if DOTNET_8_0_OR_GREATER
        stream.Write(buffer);
#else
        stream.Write(buffer, 0, buffer.Length);
#endif
    }

    public static uint ReadUint32(this Stream stream, int bytesToRead = 4)
    {
        CheckRemaining(stream, bytesToRead);
#if DOTNET_8_0_OR_GREATER
        Span<byte> buffer = stackalloc byte[bytesToRead];
        stream.Read(buffer);
#else
        byte[] buffer = new byte[bytesToRead];
        stream.Read(buffer, 0, bytesToRead);
#endif
        uint result = 0;
        uint digitMultiplier = 1;
        int posByte = bytesToRead;
        while (posByte != 0)
        {
            posByte--;
            result |= buffer[posByte] * digitMultiplier;
            digitMultiplier <<= 8;
        }

        return result;
    }

    public static ulong ReadUInt64(this Stream stream)
    {
        int bytesToRead = 8;
        CheckRemaining(stream, bytesToRead);
#if DOTNET_8_0_OR_GREATER
        Span<byte> buffer = stackalloc byte[bytesToRead];
        stream.Read(buffer);
#else
        byte[] buffer = new byte[bytesToRead];
        stream.Read(buffer, 0, bytesToRead);
#endif
        ulong result = 0;
        ulong digitMultiplier = 1;
        int posByte = bytesToRead;
        while (posByte != 0)
        {
            posByte--;
            result |= buffer[posByte] * digitMultiplier;
            digitMultiplier <<= 8;
        }

        return result;
    }

    public static void CheckRemaining(this Stream stream, int length)
    {
        if (stream.Length - stream.Position < length)
        {
            throw new StreamUnderflowException();
        }
    }

    public static void ForEach<T>(this T[] items, Action<T> action)
    {
        foreach (var item in items)
        {
            action(item);
        }
    }
}

class BigEndianStream
{
    Stream stream;

    public BigEndianStream(Stream stream)
    {
        this.stream = stream;
    }

    public bool HasRemaining()
    {
        return (stream.Length - Position) > 0;
    }

    public long Position
    {
        get => stream.Position;
        set => stream.Position = value;
    }

    public void WriteBytes(byte[] buffer)
    {
#if DOTNET_8_0_OR_GREATER
        stream.Write(buffer);
#else
        stream.Write(buffer, 0, buffer.Length);
#endif
    }

    public void WriteByte(byte value) => stream.WriteInt32(value, bytesToWrite: 1);

    public void WriteSByte(sbyte value) => stream.WriteInt32(value, bytesToWrite: 1);

    public void WriteUShort(ushort value) => stream.WriteInt32(value, bytesToWrite: 2);

    public void WriteShort(short value) => stream.WriteInt32(value, bytesToWrite: 2);

    public void WriteUInt(uint value) => stream.WriteInt32((int)value);

    public void WriteInt(int value) => stream.WriteInt32(value);

    public void WriteULong(ulong value) => stream.WriteInt64((long)value);

    public void WriteLong(long value) => stream.WriteInt64(value);

    public void WriteFloat(float value)
    {
        unsafe
        {
            WriteInt(*((int*)&value));
        }
    }

    public void WriteDouble(double value) =>
        stream.WriteInt64(BitConverter.DoubleToInt64Bits(value));

    public byte[] ReadBytes(int length)
    {
        stream.CheckRemaining(length);
        byte[] result = new byte[length];
        stream.Read(result, 0, length);
        return result;
    }

    public byte ReadByte() => (byte)stream.ReadUint32(bytesToRead: 1);

    public ushort ReadUShort() => (ushort)stream.ReadUint32(bytesToRead: 2);

    public uint ReadUInt() => (uint)stream.ReadUint32(bytesToRead: 4);

    public ulong ReadULong() => stream.ReadUInt64();

    public sbyte ReadSByte() => (sbyte)ReadByte();

    public short ReadShort() => (short)ReadUShort();

    public int ReadInt() => (int)ReadUInt();

    public float ReadFloat()
    {
        unsafe
        {
            int value = ReadInt();
            return *((float*)&value);
        }
    }

    public long ReadLong() => (long)ReadULong();

    public double ReadDouble() => BitConverter.Int64BitsToDouble(ReadLong());
}

// Contains loading, initialization code,
// and the FFI Function declarations in a com.sun.jna.Library.

// This is an implementation detail that will be called internally by the public API.
static class _UniFFILib
{
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiRustFutureContinuationCallback(ulong @data, sbyte @pollResult);

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureFree(ulong @handle);

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiCallbackInterfaceFree(ulong @handle);

    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFuture
    {
        public ulong @handle;
        public IntPtr @free;
    }

    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureStructU8
    {
        public byte @returnValue;
        public UniffiRustCallStatus @callStatus;
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteU8(
        ulong @callbackData,
        _UniFFILib.UniffiForeignFutureStructU8 @result
    );

    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureStructI8
    {
        public sbyte @returnValue;
        public UniffiRustCallStatus @callStatus;
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteI8(
        ulong @callbackData,
        _UniFFILib.UniffiForeignFutureStructI8 @result
    );

    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureStructU16
    {
        public ushort @returnValue;
        public UniffiRustCallStatus @callStatus;
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteU16(
        ulong @callbackData,
        _UniFFILib.UniffiForeignFutureStructU16 @result
    );

    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureStructI16
    {
        public short @returnValue;
        public UniffiRustCallStatus @callStatus;
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteI16(
        ulong @callbackData,
        _UniFFILib.UniffiForeignFutureStructI16 @result
    );

    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureStructU32
    {
        public uint @returnValue;
        public UniffiRustCallStatus @callStatus;
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteU32(
        ulong @callbackData,
        _UniFFILib.UniffiForeignFutureStructU32 @result
    );

    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureStructI32
    {
        public int @returnValue;
        public UniffiRustCallStatus @callStatus;
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteI32(
        ulong @callbackData,
        _UniFFILib.UniffiForeignFutureStructI32 @result
    );

    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureStructU64
    {
        public ulong @returnValue;
        public UniffiRustCallStatus @callStatus;
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteU64(
        ulong @callbackData,
        _UniFFILib.UniffiForeignFutureStructU64 @result
    );

    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureStructI64
    {
        public long @returnValue;
        public UniffiRustCallStatus @callStatus;
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteI64(
        ulong @callbackData,
        _UniFFILib.UniffiForeignFutureStructI64 @result
    );

    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureStructF32
    {
        public float @returnValue;
        public UniffiRustCallStatus @callStatus;
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteF32(
        ulong @callbackData,
        _UniFFILib.UniffiForeignFutureStructF32 @result
    );

    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureStructF64
    {
        public double @returnValue;
        public UniffiRustCallStatus @callStatus;
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteF64(
        ulong @callbackData,
        _UniFFILib.UniffiForeignFutureStructF64 @result
    );

    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureStructPointer
    {
        public IntPtr @returnValue;
        public UniffiRustCallStatus @callStatus;
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompletePointer(
        ulong @callbackData,
        _UniFFILib.UniffiForeignFutureStructPointer @result
    );

    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureStructRustBuffer
    {
        public RustBuffer @returnValue;
        public UniffiRustCallStatus @callStatus;
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteRustBuffer(
        ulong @callbackData,
        _UniFFILib.UniffiForeignFutureStructRustBuffer @result
    );

    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureStructVoid
    {
        public UniffiRustCallStatus @callStatus;
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteVoid(
        ulong @callbackData,
        _UniFFILib.UniffiForeignFutureStructVoid @result
    );

    static _UniFFILib()
    {
        _UniFFILib.uniffiCheckContractApiVersion();
        _UniFFILib.uniffiCheckApiChecksums();
    }

    [DllImport("duper_uniffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern RustBuffer uniffi_duper_uniffi_fn_func_parse(
        RustBuffer @input,
        sbyte @parseAny,
        ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("duper_uniffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern RustBuffer uniffi_duper_uniffi_fn_func_serialize(
        RustBuffer @input,
        RustBuffer @options,
        ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("duper_uniffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern RustBuffer ffi_duper_uniffi_rustbuffer_alloc(
        ulong @size,
        ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("duper_uniffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern RustBuffer ffi_duper_uniffi_rustbuffer_from_bytes(
        ForeignBytes @bytes,
        ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("duper_uniffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_duper_uniffi_rustbuffer_free(
        RustBuffer @buf,
        ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("duper_uniffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern RustBuffer ffi_duper_uniffi_rustbuffer_reserve(
        RustBuffer @buf,
        ulong @additional,
        ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("duper_uniffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_duper_uniffi_rust_future_poll_u8(
        IntPtr @handle,
        IntPtr @callback,
        IntPtr @callbackData
    );

    [DllImport("duper_uniffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_duper_uniffi_rust_future_cancel_u8(IntPtr @handle);

    [DllImport("duper_uniffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_duper_uniffi_rust_future_free_u8(IntPtr @handle);

    [DllImport("duper_uniffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern byte ffi_duper_uniffi_rust_future_complete_u8(
        IntPtr @handle,
        ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("duper_uniffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_duper_uniffi_rust_future_poll_i8(
        IntPtr @handle,
        IntPtr @callback,
        IntPtr @callbackData
    );

    [DllImport("duper_uniffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_duper_uniffi_rust_future_cancel_i8(IntPtr @handle);

    [DllImport("duper_uniffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_duper_uniffi_rust_future_free_i8(IntPtr @handle);

    [DllImport("duper_uniffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern sbyte ffi_duper_uniffi_rust_future_complete_i8(
        IntPtr @handle,
        ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("duper_uniffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_duper_uniffi_rust_future_poll_u16(
        IntPtr @handle,
        IntPtr @callback,
        IntPtr @callbackData
    );

    [DllImport("duper_uniffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_duper_uniffi_rust_future_cancel_u16(IntPtr @handle);

    [DllImport("duper_uniffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_duper_uniffi_rust_future_free_u16(IntPtr @handle);

    [DllImport("duper_uniffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern ushort ffi_duper_uniffi_rust_future_complete_u16(
        IntPtr @handle,
        ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("duper_uniffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_duper_uniffi_rust_future_poll_i16(
        IntPtr @handle,
        IntPtr @callback,
        IntPtr @callbackData
    );

    [DllImport("duper_uniffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_duper_uniffi_rust_future_cancel_i16(IntPtr @handle);

    [DllImport("duper_uniffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_duper_uniffi_rust_future_free_i16(IntPtr @handle);

    [DllImport("duper_uniffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern short ffi_duper_uniffi_rust_future_complete_i16(
        IntPtr @handle,
        ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("duper_uniffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_duper_uniffi_rust_future_poll_u32(
        IntPtr @handle,
        IntPtr @callback,
        IntPtr @callbackData
    );

    [DllImport("duper_uniffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_duper_uniffi_rust_future_cancel_u32(IntPtr @handle);

    [DllImport("duper_uniffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_duper_uniffi_rust_future_free_u32(IntPtr @handle);

    [DllImport("duper_uniffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern uint ffi_duper_uniffi_rust_future_complete_u32(
        IntPtr @handle,
        ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("duper_uniffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_duper_uniffi_rust_future_poll_i32(
        IntPtr @handle,
        IntPtr @callback,
        IntPtr @callbackData
    );

    [DllImport("duper_uniffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_duper_uniffi_rust_future_cancel_i32(IntPtr @handle);

    [DllImport("duper_uniffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_duper_uniffi_rust_future_free_i32(IntPtr @handle);

    [DllImport("duper_uniffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern int ffi_duper_uniffi_rust_future_complete_i32(
        IntPtr @handle,
        ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("duper_uniffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_duper_uniffi_rust_future_poll_u64(
        IntPtr @handle,
        IntPtr @callback,
        IntPtr @callbackData
    );

    [DllImport("duper_uniffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_duper_uniffi_rust_future_cancel_u64(IntPtr @handle);

    [DllImport("duper_uniffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_duper_uniffi_rust_future_free_u64(IntPtr @handle);

    [DllImport("duper_uniffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern ulong ffi_duper_uniffi_rust_future_complete_u64(
        IntPtr @handle,
        ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("duper_uniffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_duper_uniffi_rust_future_poll_i64(
        IntPtr @handle,
        IntPtr @callback,
        IntPtr @callbackData
    );

    [DllImport("duper_uniffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_duper_uniffi_rust_future_cancel_i64(IntPtr @handle);

    [DllImport("duper_uniffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_duper_uniffi_rust_future_free_i64(IntPtr @handle);

    [DllImport("duper_uniffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern long ffi_duper_uniffi_rust_future_complete_i64(
        IntPtr @handle,
        ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("duper_uniffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_duper_uniffi_rust_future_poll_f32(
        IntPtr @handle,
        IntPtr @callback,
        IntPtr @callbackData
    );

    [DllImport("duper_uniffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_duper_uniffi_rust_future_cancel_f32(IntPtr @handle);

    [DllImport("duper_uniffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_duper_uniffi_rust_future_free_f32(IntPtr @handle);

    [DllImport("duper_uniffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern float ffi_duper_uniffi_rust_future_complete_f32(
        IntPtr @handle,
        ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("duper_uniffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_duper_uniffi_rust_future_poll_f64(
        IntPtr @handle,
        IntPtr @callback,
        IntPtr @callbackData
    );

    [DllImport("duper_uniffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_duper_uniffi_rust_future_cancel_f64(IntPtr @handle);

    [DllImport("duper_uniffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_duper_uniffi_rust_future_free_f64(IntPtr @handle);

    [DllImport("duper_uniffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern double ffi_duper_uniffi_rust_future_complete_f64(
        IntPtr @handle,
        ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("duper_uniffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_duper_uniffi_rust_future_poll_pointer(
        IntPtr @handle,
        IntPtr @callback,
        IntPtr @callbackData
    );

    [DllImport("duper_uniffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_duper_uniffi_rust_future_cancel_pointer(IntPtr @handle);

    [DllImport("duper_uniffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_duper_uniffi_rust_future_free_pointer(IntPtr @handle);

    [DllImport("duper_uniffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr ffi_duper_uniffi_rust_future_complete_pointer(
        IntPtr @handle,
        ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("duper_uniffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_duper_uniffi_rust_future_poll_rust_buffer(
        IntPtr @handle,
        IntPtr @callback,
        IntPtr @callbackData
    );

    [DllImport("duper_uniffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_duper_uniffi_rust_future_cancel_rust_buffer(IntPtr @handle);

    [DllImport("duper_uniffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_duper_uniffi_rust_future_free_rust_buffer(IntPtr @handle);

    [DllImport("duper_uniffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern RustBuffer ffi_duper_uniffi_rust_future_complete_rust_buffer(
        IntPtr @handle,
        ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("duper_uniffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_duper_uniffi_rust_future_poll_void(
        IntPtr @handle,
        IntPtr @callback,
        IntPtr @callbackData
    );

    [DllImport("duper_uniffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_duper_uniffi_rust_future_cancel_void(IntPtr @handle);

    [DllImport("duper_uniffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_duper_uniffi_rust_future_free_void(IntPtr @handle);

    [DllImport("duper_uniffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_duper_uniffi_rust_future_complete_void(
        IntPtr @handle,
        ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("duper_uniffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern ushort uniffi_duper_uniffi_checksum_func_parse();

    [DllImport("duper_uniffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern ushort uniffi_duper_uniffi_checksum_func_serialize();

    [DllImport("duper_uniffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern uint ffi_duper_uniffi_uniffi_contract_version();

    static void uniffiCheckContractApiVersion()
    {
        var scaffolding_contract_version = _UniFFILib.ffi_duper_uniffi_uniffi_contract_version();
        if (29 != scaffolding_contract_version)
        {
            throw new UniffiContractVersionException(
                $"Duper.Ffi: uniffi bindings expected version `29`, library returned `{scaffolding_contract_version}`"
            );
        }
    }

    static void uniffiCheckApiChecksums()
    {
        {
            var checksum = _UniFFILib.uniffi_duper_uniffi_checksum_func_parse();
            if (checksum != 8398)
            {
                throw new UniffiContractChecksumException(
                    $"Duper.Ffi: uniffi bindings expected function `uniffi_duper_uniffi_checksum_func_parse` checksum `8398`, library returned `{checksum}`"
                );
            }
        }
        {
            var checksum = _UniFFILib.uniffi_duper_uniffi_checksum_func_serialize();
            if (checksum != 14365)
            {
                throw new UniffiContractChecksumException(
                    $"Duper.Ffi: uniffi bindings expected function `uniffi_duper_uniffi_checksum_func_serialize` checksum `14365`, library returned `{checksum}`"
                );
            }
        }
    }
}

// Public interface members begin here.

#pragma warning disable 8625

class FfiConverterInt64 : FfiConverter<long, long>
{
    public static FfiConverterInt64 INSTANCE = new FfiConverterInt64();

    public override long Lift(long value)
    {
        return value;
    }

    public override long Read(BigEndianStream stream)
    {
        return stream.ReadLong();
    }

    public override long Lower(long value)
    {
        return value;
    }

    public override int AllocationSize(long value)
    {
        return 8;
    }

    public override void Write(long value, BigEndianStream stream)
    {
        stream.WriteLong(value);
    }
}

class FfiConverterDouble : FfiConverter<double, double>
{
    public static FfiConverterDouble INSTANCE = new FfiConverterDouble();

    public override double Lift(double value)
    {
        return value;
    }

    public override double Read(BigEndianStream stream)
    {
        return stream.ReadDouble();
    }

    public override double Lower(double value)
    {
        return value;
    }

    public override int AllocationSize(double value)
    {
        return 8;
    }

    public override void Write(double value, BigEndianStream stream)
    {
        stream.WriteDouble(value);
    }
}

class FfiConverterBoolean : FfiConverter<bool, sbyte>
{
    public static FfiConverterBoolean INSTANCE = new FfiConverterBoolean();

    public override bool Lift(sbyte value)
    {
        return value != 0;
    }

    public override bool Read(BigEndianStream stream)
    {
        return Lift(stream.ReadSByte());
    }

    public override sbyte Lower(bool value)
    {
        return value ? (sbyte)1 : (sbyte)0;
    }

    public override int AllocationSize(bool value)
    {
        return (sbyte)1;
    }

    public override void Write(bool value, BigEndianStream stream)
    {
        stream.WriteSByte(Lower(value));
    }
}

class FfiConverterString : FfiConverter<string, RustBuffer>
{
    public static FfiConverterString INSTANCE = new FfiConverterString();

    // Note: we don't inherit from FfiConverterRustBuffer, because we use a
    // special encoding when lowering/lifting.  We can use `RustBuffer.len` to
    // store our length and avoid writing it out to the buffer.
    public override string Lift(RustBuffer value)
    {
        try
        {
            var bytes = value.AsStream().ReadBytes(Convert.ToInt32(value.len));
            return System.Text.Encoding.UTF8.GetString(bytes);
        }
        finally
        {
            RustBuffer.Free(value);
        }
    }

    public override string Read(BigEndianStream stream)
    {
        var length = stream.ReadInt();
        var bytes = stream.ReadBytes(length);
        return System.Text.Encoding.UTF8.GetString(bytes);
    }

    public override RustBuffer Lower(string value)
    {
        var bytes = System.Text.Encoding.UTF8.GetBytes(value);
        var rbuf = RustBuffer.Alloc(bytes.Length);
        rbuf.AsWriteableStream().WriteBytes(bytes);
        return rbuf;
    }

    // TODO(CS)
    // We aren't sure exactly how many bytes our string will be once it's UTF-8
    // encoded.  Allocate 3 bytes per unicode codepoint which will always be
    // enough.
    public override int AllocationSize(string value)
    {
        const int sizeForLength = 4;
        var sizeForString = System.Text.Encoding.UTF8.GetByteCount(value);
        return sizeForLength + sizeForString;
    }

    public override void Write(string value, BigEndianStream stream)
    {
        var bytes = System.Text.Encoding.UTF8.GetBytes(value);
        stream.WriteInt(bytes.Length);
        stream.WriteBytes(bytes);
    }
}

class FfiConverterByteArray : FfiConverterRustBuffer<byte[]>
{
    public static FfiConverterByteArray INSTANCE = new FfiConverterByteArray();

    public override byte[] Read(BigEndianStream stream)
    {
        var length = stream.ReadInt();
        return stream.ReadBytes(length);
    }

    public override int AllocationSize(byte[] value)
    {
        return 4 + value.Length;
    }

    public override void Write(byte[] value, BigEndianStream stream)
    {
        stream.WriteInt(value.Length);
        stream.WriteBytes(value);
    }
}

internal record SerializeOptions(string? @indent, bool @stripIdentifiers, bool @minify) { }

class FfiConverterTypeSerializeOptions : FfiConverterRustBuffer<SerializeOptions>
{
    public static FfiConverterTypeSerializeOptions INSTANCE =
        new FfiConverterTypeSerializeOptions();

    public override SerializeOptions Read(BigEndianStream stream)
    {
        return new SerializeOptions(
            @indent: FfiConverterOptionalString.INSTANCE.Read(stream),
            @stripIdentifiers: FfiConverterBoolean.INSTANCE.Read(stream),
            @minify: FfiConverterBoolean.INSTANCE.Read(stream)
        );
    }

    public override int AllocationSize(SerializeOptions value)
    {
        return 0
            + FfiConverterOptionalString.INSTANCE.AllocationSize(value.@indent)
            + FfiConverterBoolean.INSTANCE.AllocationSize(value.@stripIdentifiers)
            + FfiConverterBoolean.INSTANCE.AllocationSize(value.@minify);
    }

    public override void Write(SerializeOptions value, BigEndianStream stream)
    {
        FfiConverterOptionalString.INSTANCE.Write(value.@indent, stream);
        FfiConverterBoolean.INSTANCE.Write(value.@stripIdentifiers, stream);
        FfiConverterBoolean.INSTANCE.Write(value.@minify, stream);
    }
}

internal class DuperException : UniffiException
{
    DuperException(string message)
        : base(message) { }

    // Each variant is a nested class
    // Flat enums carries a string error message, so no special implementation is necessary.

    public class Parse : DuperException
    {
        public Parse(string message)
            : base(message) { }
    }

    public class SerializeOptions : DuperException
    {
        public SerializeOptions(string message)
            : base(message) { }
    }

    public class InvalidIdentifier : DuperException
    {
        public InvalidIdentifier(string message)
            : base(message) { }
    }

    public class InvalidObject : DuperException
    {
        public InvalidObject(string message)
            : base(message) { }
    }

    public class InvalidTemporal : DuperException
    {
        public InvalidTemporal(string message)
            : base(message) { }
    }
}

class FfiConverterTypeDuperError
    : FfiConverterRustBuffer<DuperException>,
        CallStatusErrorHandler<DuperException>
{
    public static FfiConverterTypeDuperError INSTANCE = new FfiConverterTypeDuperError();

    public override DuperException Read(BigEndianStream stream)
    {
        var value = stream.ReadInt();
        switch (value)
        {
            case 1:
                return new DuperException.Parse(FfiConverterString.INSTANCE.Read(stream));
            case 2:
                return new DuperException.SerializeOptions(
                    FfiConverterString.INSTANCE.Read(stream)
                );
            case 3:
                return new DuperException.InvalidIdentifier(
                    FfiConverterString.INSTANCE.Read(stream)
                );
            case 4:
                return new DuperException.InvalidObject(FfiConverterString.INSTANCE.Read(stream));
            case 5:
                return new DuperException.InvalidTemporal(FfiConverterString.INSTANCE.Read(stream));
            default:
                throw new InternalException(
                    String.Format(
                        "invalid error value '{0}' in FfiConverterTypeDuperError.Read()",
                        value
                    )
                );
        }
    }

    public override int AllocationSize(DuperException value)
    {
        return 4 + FfiConverterString.INSTANCE.AllocationSize(value.Message);
    }

    public override void Write(DuperException value, BigEndianStream stream)
    {
        switch (value)
        {
            case DuperException.Parse:
                stream.WriteInt(1);
                break;
            case DuperException.SerializeOptions:
                stream.WriteInt(2);
                break;
            case DuperException.InvalidIdentifier:
                stream.WriteInt(3);
                break;
            case DuperException.InvalidObject:
                stream.WriteInt(4);
                break;
            case DuperException.InvalidTemporal:
                stream.WriteInt(5);
                break;
            default:
                throw new InternalException(
                    String.Format(
                        "invalid error value '{0}' in FfiConverterTypeDuperError.Write()",
                        value
                    )
                );
        }
    }
}

internal record DuperValue
{
    public record Object(string? @identifier, Dictionary<string, DuperValue> @value)
        : DuperValue { }

    public record Array(string? @identifier, DuperValue[] @value) : DuperValue { }

    public record Tuple(string? @identifier, DuperValue[] @value) : DuperValue { }

    public record String(string? @identifier, string @value) : DuperValue { }

    public record Bytes(string? @identifier, byte[] @value) : DuperValue { }

    public record Temporal(string? @identifier, string @value) : DuperValue { }

    public record Integer(string? @identifier, long @value) : DuperValue { }

    public record Float(string? @identifier, double @value) : DuperValue { }

    public record Boolean(string? @identifier, bool @value) : DuperValue { }

    public record Null(string? @identifier) : DuperValue { }
}

class FfiConverterTypeDuperValue : FfiConverterRustBuffer<DuperValue>
{
    public static FfiConverterRustBuffer<DuperValue> INSTANCE = new FfiConverterTypeDuperValue();

    public override DuperValue Read(BigEndianStream stream)
    {
        var value = stream.ReadInt();
        switch (value)
        {
            case 1:
                return new DuperValue.Object(
                    FfiConverterOptionalString.INSTANCE.Read(stream),
                    FfiConverterDictionaryStringTypeDuperValue.INSTANCE.Read(stream)
                );
            case 2:
                return new DuperValue.Array(
                    FfiConverterOptionalString.INSTANCE.Read(stream),
                    FfiConverterSequenceTypeDuperValue.INSTANCE.Read(stream)
                );
            case 3:
                return new DuperValue.Tuple(
                    FfiConverterOptionalString.INSTANCE.Read(stream),
                    FfiConverterSequenceTypeDuperValue.INSTANCE.Read(stream)
                );
            case 4:
                return new DuperValue.String(
                    FfiConverterOptionalString.INSTANCE.Read(stream),
                    FfiConverterString.INSTANCE.Read(stream)
                );
            case 5:
                return new DuperValue.Bytes(
                    FfiConverterOptionalString.INSTANCE.Read(stream),
                    FfiConverterByteArray.INSTANCE.Read(stream)
                );
            case 6:
                return new DuperValue.Temporal(
                    FfiConverterOptionalString.INSTANCE.Read(stream),
                    FfiConverterString.INSTANCE.Read(stream)
                );
            case 7:
                return new DuperValue.Integer(
                    FfiConverterOptionalString.INSTANCE.Read(stream),
                    FfiConverterInt64.INSTANCE.Read(stream)
                );
            case 8:
                return new DuperValue.Float(
                    FfiConverterOptionalString.INSTANCE.Read(stream),
                    FfiConverterDouble.INSTANCE.Read(stream)
                );
            case 9:
                return new DuperValue.Boolean(
                    FfiConverterOptionalString.INSTANCE.Read(stream),
                    FfiConverterBoolean.INSTANCE.Read(stream)
                );
            case 10:
                return new DuperValue.Null(FfiConverterOptionalString.INSTANCE.Read(stream));
            default:
                throw new InternalException(
                    String.Format(
                        "invalid enum value '{0}' in FfiConverterTypeDuperValue.Read()",
                        value
                    )
                );
        }
    }

    public override int AllocationSize(DuperValue value)
    {
        switch (value)
        {
            case DuperValue.Object variant_value:
                return 4
                    + FfiConverterOptionalString.INSTANCE.AllocationSize(variant_value.@identifier)
                    + FfiConverterDictionaryStringTypeDuperValue.INSTANCE.AllocationSize(
                        variant_value.@value
                    );
            case DuperValue.Array variant_value:
                return 4
                    + FfiConverterOptionalString.INSTANCE.AllocationSize(variant_value.@identifier)
                    + FfiConverterSequenceTypeDuperValue.INSTANCE.AllocationSize(
                        variant_value.@value
                    );
            case DuperValue.Tuple variant_value:
                return 4
                    + FfiConverterOptionalString.INSTANCE.AllocationSize(variant_value.@identifier)
                    + FfiConverterSequenceTypeDuperValue.INSTANCE.AllocationSize(
                        variant_value.@value
                    );
            case DuperValue.String variant_value:
                return 4
                    + FfiConverterOptionalString.INSTANCE.AllocationSize(variant_value.@identifier)
                    + FfiConverterString.INSTANCE.AllocationSize(variant_value.@value);
            case DuperValue.Bytes variant_value:
                return 4
                    + FfiConverterOptionalString.INSTANCE.AllocationSize(variant_value.@identifier)
                    + FfiConverterByteArray.INSTANCE.AllocationSize(variant_value.@value);
            case DuperValue.Temporal variant_value:
                return 4
                    + FfiConverterOptionalString.INSTANCE.AllocationSize(variant_value.@identifier)
                    + FfiConverterString.INSTANCE.AllocationSize(variant_value.@value);
            case DuperValue.Integer variant_value:
                return 4
                    + FfiConverterOptionalString.INSTANCE.AllocationSize(variant_value.@identifier)
                    + FfiConverterInt64.INSTANCE.AllocationSize(variant_value.@value);
            case DuperValue.Float variant_value:
                return 4
                    + FfiConverterOptionalString.INSTANCE.AllocationSize(variant_value.@identifier)
                    + FfiConverterDouble.INSTANCE.AllocationSize(variant_value.@value);
            case DuperValue.Boolean variant_value:
                return 4
                    + FfiConverterOptionalString.INSTANCE.AllocationSize(variant_value.@identifier)
                    + FfiConverterBoolean.INSTANCE.AllocationSize(variant_value.@value);
            case DuperValue.Null variant_value:
                return 4
                    + FfiConverterOptionalString.INSTANCE.AllocationSize(variant_value.@identifier);
            default:
                throw new InternalException(
                    String.Format(
                        "invalid enum value '{0}' in FfiConverterTypeDuperValue.AllocationSize()",
                        value
                    )
                );
        }
    }

    public override void Write(DuperValue value, BigEndianStream stream)
    {
        switch (value)
        {
            case DuperValue.Object variant_value:
                stream.WriteInt(1);
                FfiConverterOptionalString.INSTANCE.Write(variant_value.@identifier, stream);
                FfiConverterDictionaryStringTypeDuperValue.INSTANCE.Write(
                    variant_value.@value,
                    stream
                );
                break;
            case DuperValue.Array variant_value:
                stream.WriteInt(2);
                FfiConverterOptionalString.INSTANCE.Write(variant_value.@identifier, stream);
                FfiConverterSequenceTypeDuperValue.INSTANCE.Write(variant_value.@value, stream);
                break;
            case DuperValue.Tuple variant_value:
                stream.WriteInt(3);
                FfiConverterOptionalString.INSTANCE.Write(variant_value.@identifier, stream);
                FfiConverterSequenceTypeDuperValue.INSTANCE.Write(variant_value.@value, stream);
                break;
            case DuperValue.String variant_value:
                stream.WriteInt(4);
                FfiConverterOptionalString.INSTANCE.Write(variant_value.@identifier, stream);
                FfiConverterString.INSTANCE.Write(variant_value.@value, stream);
                break;
            case DuperValue.Bytes variant_value:
                stream.WriteInt(5);
                FfiConverterOptionalString.INSTANCE.Write(variant_value.@identifier, stream);
                FfiConverterByteArray.INSTANCE.Write(variant_value.@value, stream);
                break;
            case DuperValue.Temporal variant_value:
                stream.WriteInt(6);
                FfiConverterOptionalString.INSTANCE.Write(variant_value.@identifier, stream);
                FfiConverterString.INSTANCE.Write(variant_value.@value, stream);
                break;
            case DuperValue.Integer variant_value:
                stream.WriteInt(7);
                FfiConverterOptionalString.INSTANCE.Write(variant_value.@identifier, stream);
                FfiConverterInt64.INSTANCE.Write(variant_value.@value, stream);
                break;
            case DuperValue.Float variant_value:
                stream.WriteInt(8);
                FfiConverterOptionalString.INSTANCE.Write(variant_value.@identifier, stream);
                FfiConverterDouble.INSTANCE.Write(variant_value.@value, stream);
                break;
            case DuperValue.Boolean variant_value:
                stream.WriteInt(9);
                FfiConverterOptionalString.INSTANCE.Write(variant_value.@identifier, stream);
                FfiConverterBoolean.INSTANCE.Write(variant_value.@value, stream);
                break;
            case DuperValue.Null variant_value:
                stream.WriteInt(10);
                FfiConverterOptionalString.INSTANCE.Write(variant_value.@identifier, stream);
                break;
            default:
                throw new InternalException(
                    String.Format(
                        "invalid enum value '{0}' in FfiConverterTypeDuperValue.Write()",
                        value
                    )
                );
        }
    }
}

class FfiConverterOptionalString : FfiConverterRustBuffer<string?>
{
    public static FfiConverterOptionalString INSTANCE = new FfiConverterOptionalString();

    public override string? Read(BigEndianStream stream)
    {
        if (stream.ReadByte() == 0)
        {
            return null;
        }
        return FfiConverterString.INSTANCE.Read(stream);
    }

    public override int AllocationSize(string? value)
    {
        if (value == null)
        {
            return 1;
        }
        else
        {
            return 1 + FfiConverterString.INSTANCE.AllocationSize((string)value);
        }
    }

    public override void Write(string? value, BigEndianStream stream)
    {
        if (value == null)
        {
            stream.WriteByte(0);
        }
        else
        {
            stream.WriteByte(1);
            FfiConverterString.INSTANCE.Write((string)value, stream);
        }
    }
}

class FfiConverterOptionalTypeSerializeOptions : FfiConverterRustBuffer<SerializeOptions?>
{
    public static FfiConverterOptionalTypeSerializeOptions INSTANCE =
        new FfiConverterOptionalTypeSerializeOptions();

    public override SerializeOptions? Read(BigEndianStream stream)
    {
        if (stream.ReadByte() == 0)
        {
            return null;
        }
        return FfiConverterTypeSerializeOptions.INSTANCE.Read(stream);
    }

    public override int AllocationSize(SerializeOptions? value)
    {
        if (value == null)
        {
            return 1;
        }
        else
        {
            return 1
                + FfiConverterTypeSerializeOptions.INSTANCE.AllocationSize((SerializeOptions)value);
        }
    }

    public override void Write(SerializeOptions? value, BigEndianStream stream)
    {
        if (value == null)
        {
            stream.WriteByte(0);
        }
        else
        {
            stream.WriteByte(1);
            FfiConverterTypeSerializeOptions.INSTANCE.Write((SerializeOptions)value, stream);
        }
    }
}

class FfiConverterSequenceTypeDuperValue : FfiConverterRustBuffer<DuperValue[]>
{
    public static FfiConverterSequenceTypeDuperValue INSTANCE =
        new FfiConverterSequenceTypeDuperValue();

    public override DuperValue[] Read(BigEndianStream stream)
    {
        var length = stream.ReadInt();
        if (length == 0)
        {
            return [];
        }

        var result = new DuperValue[(length)];
        var readFn = FfiConverterTypeDuperValue.INSTANCE.Read;
        for (int i = 0; i < length; i++)
        {
            result[i] = readFn(stream);
        }
        return result;
    }

    public override int AllocationSize(DuperValue[] value)
    {
        var sizeForLength = 4;

        // details/1-empty-list-as-default-method-parameter.md
        if (value == null)
        {
            return sizeForLength;
        }

        var allocationSizeFn = FfiConverterTypeDuperValue.INSTANCE.AllocationSize;
        var sizeForItems = value.Sum(item => allocationSizeFn(item));
        return sizeForLength + sizeForItems;
    }

    public override void Write(DuperValue[] value, BigEndianStream stream)
    {
        // details/1-empty-list-as-default-method-parameter.md
        if (value == null)
        {
            stream.WriteInt(0);
            return;
        }

        stream.WriteInt(value.Length);
        var writerFn = FfiConverterTypeDuperValue.INSTANCE.Write;
        value.ForEach(item => writerFn(item, stream));
    }
}

class FfiConverterDictionaryStringTypeDuperValue
    : FfiConverterRustBuffer<Dictionary<string, DuperValue>>
{
    public static FfiConverterDictionaryStringTypeDuperValue INSTANCE =
        new FfiConverterDictionaryStringTypeDuperValue();

    public override Dictionary<string, DuperValue> Read(BigEndianStream stream)
    {
        var len = stream.ReadInt();
        var result = new Dictionary<string, DuperValue>(len);
        var readerKey = FfiConverterString.INSTANCE.Read;
        var readerValue = FfiConverterTypeDuperValue.INSTANCE.Read;
        for (int i = 0; i < len; i++)
        {
            var key = readerKey(stream);
            var value = readerValue(stream);
            result[key] = value;
        }

        return result;
    }

    public override int AllocationSize(Dictionary<string, DuperValue> value)
    {
        var sizeForLength = 4;

        // details/1-empty-list-as-default-method-parameter.md
        if (value == null)
        {
            return sizeForLength;
        }

        var allocationKeySizeFn = FfiConverterString.INSTANCE.AllocationSize;
        var allocationKValueSizeFn = FfiConverterTypeDuperValue.INSTANCE.AllocationSize;
        var sizeForItems = value.Sum(item =>
            allocationKeySizeFn(item.Key) + allocationKValueSizeFn(item.Value)
        );
        return sizeForLength + sizeForItems;
    }

    public override void Write(Dictionary<string, DuperValue> value, BigEndianStream stream)
    {
        // details/1-empty-list-as-default-method-parameter.md
        if (value == null)
        {
            stream.WriteInt(0);
            return;
        }

        stream.WriteInt(value.Count);
        var writerKey = FfiConverterString.INSTANCE.Write;
        var writerValue = FfiConverterTypeDuperValue.INSTANCE.Write;
        foreach (var item in value)
        {
            writerKey(item.Key, stream);
            writerValue(item.Value, stream);
        }
    }
}
#pragma warning restore 8625
internal static class Duper
{
    /// <exception cref="DuperException"></exception>
    public static DuperValue Parse(string @input, bool @parseAny)
    {
        return FfiConverterTypeDuperValue.INSTANCE.Lift(
            _UniffiHelpers.RustCallWithError(
                FfiConverterTypeDuperError.INSTANCE,
                (ref UniffiRustCallStatus _status) =>
                    _UniFFILib.uniffi_duper_uniffi_fn_func_parse(
                        FfiConverterString.INSTANCE.Lower(@input),
                        FfiConverterBoolean.INSTANCE.Lower(@parseAny),
                        ref _status
                    )
            )
        );
    }

    /// <exception cref="DuperException"></exception>
    public static string Serialize(DuperValue @input, SerializeOptions? @options)
    {
        return FfiConverterString.INSTANCE.Lift(
            _UniffiHelpers.RustCallWithError(
                FfiConverterTypeDuperError.INSTANCE,
                (ref UniffiRustCallStatus _status) =>
                    _UniFFILib.uniffi_duper_uniffi_fn_func_serialize(
                        FfiConverterTypeDuperValue.INSTANCE.Lower(@input),
                        FfiConverterOptionalTypeSerializeOptions.INSTANCE.Lower(@options),
                        ref _status
                    )
            )
        );
    }
}
