[package]
name = "duper-python"
description = "The format that's super!"
version = "0.3.0"
edition = "2024"
rust-version = "1.88"
license = "MIT"
authors = ["Eric Rodrigues Pires <eric@eric.dev.br>"]
repository = "https://github.com/EpicEric/duper"
homepage = "https://duper.dev.br"
readme = "README.md"
categories = ["encoding", "parser-implementations"]
keywords = ["duper", "serialization", "python"]
publish = false

[lib]
name = "_duper"
crate-type = ["cdylib"]

[dependencies]
duper = { path = "../duper" }
pyo3 = { version = "0.27.1", features = [
  "extension-module",
  "generate-import-lib",
] }
