default:
  just --list

bindgen:
  uniffi-bindgen-cs src/duper.udl --config uniffi.toml --out-dir dotnet

build-debug:
  cargo build

build-release:
  cargo build --release --target x86_64-unknown-linux-gnu
  cargo build --release --target x86_64-pc-windows-gnu

[working-directory: 'dotnet']
package-dotnet: build-release bindgen
  dotnet build
  dotnet pack

test: build-debug bindgen test-dotnet

[working-directory: 'tests/dotnet']
test-dotnet:
  dotnet test
