default:
  just --list

bindgen-debug:
  cargo build
  uniffi-bindgen-cs src/duper.udl --config uniffi.toml --out-dir csharp/ffi

bindgen-release:
  cargo build --release --target x86_64-unknown-linux-gnu
  uniffi-bindgen-cs src/duper.udl --config uniffi.toml --out-dir csharp/ffi

example: bindgen-release example-cs

[working-directory: 'example/csharp']
example-cs:
  dotnet build
  LD_LIBRARY_PATH="../../../target/x86_64-unknown-linux-gnu/release" dotnet run
