default:
  just --list

bindgen:
  uniffi-bindgen-cs src/duper.udl --config uniffi.toml --out-dir csharp

build-debug:
  cargo build

build-release:
  cargo build --release --target x86_64-unknown-linux-gnu
  cargo build --release --target x86_64-pc-windows-gnu

[working-directory: 'csharp']
package-cs: build-release bindgen
  dotnet build
  dotnet pack

example: build-debug bindgen example-cs

[working-directory: 'example/csharp']
example-cs:
  dotnet run

test: build-debug bindgen test-cs

[working-directory: 'tests/csharp']
test-cs:
  dotnet test
